### ISSUE TITLE
Installation script seems bugged

### ISSUE THREAD

**Issue by JulienPerrin** [athul/pwcli#52]
Hello, 

I tried to install through the script on Windows 10 (with WSL2) and then on a Linux VM (Ubuntu 20.04.3 LTS) without success. It prints the version and does nothing else : 

```
julien@julien-VirtualBox:~$ sudo sh -c "$(curl -sL https://git.io/getpwcli)"
[sudo] Mot de passe de julien : 
athul/pwcli info checking GitHub for latest tag
athul/pwcli info found version: 0.0.8 for v0.0.8/Linux/x86_64
julien@julien-VirtualBox:~$ hopp-cli --help
hopp-cli : commande introuvable
julien@julien-VirtualBox:~$ 
```

I think the script is bugged. 
Installation worked fine through downloading the release manually. 

By the way what is pwcli ?

**Comment by athul** [comment]
Hey, I checked this and this is due to a few reasons
- This project was earlier on my personal account when I made the installation script
- I used [GoDownloader](https://github.com/goreleaser/godownloader) which was later deprecated.
- Godownloader didn't seem to work when I tried to create a new link for this new repo in when it was moved to the org(It did work for some time)


> By the way what is pwcli ?

`pwcli` was the initial name given to the cli since the current hoppscotch project used to be called postwoman  😝(postwoman's `pw` and CLI's well cli)

**Comment by athul** [comment]
Hey, I checked this and this is due to a few reasons
- This project was earlier on my personal account when I made the installation script
- I used [GoDownloader](https://github.com/goreleaser/godownloader) which was later deprecated.
- Godownloader didn't seem to work when I tried to create a new link for this new repo in when it was moved to the org(It did work for some time)


> By the way what is pwcli ?

`pwcli` was the initial name given to the cli since the current hoppscotch project used to be called postwoman  😝(postwoman's `pw` and CLI's well cli)

**Comment by JulienPerrin** [comment]
Thanks for your answer. 
I guess the installation through script is bugged then. Maybe remove it from the readme. 
Installation worked well through binaries for me though. 

Nice name. 😸
